// Configuration globale pour Font Awesome
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faChartLine,
  faFileAlt,
  faEye,
  faFileDownload,
  faCog,
  faChartBar,
  faPercentage,
  faPaperPlane,
  faRotateLeft,
  faImage,
  faLink,
  faAd,
  faServer,
  faClock,
  faSearch,
  faFilter,
  faFilePdf,
  faFileCsv,
  faTrophy,
  faUser,
  faLock,
  faUserShield,
  faHistory,
  faExclamationTriangle,
  faSignOutAlt,
  faUserPlus,
  faSave,
  faTrash,
  faHeart,
  faComment,
  faShare,
  faThumbsUp,
  faBars,
  faHome,
  faEnvelope,
  faPhone,
  faCalendar,
  faDownload,
  faUpload,
  faEdit,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
} from '@fortawesome/free-solid-svg-icons';

import {
  faYoutube,
  faFacebook,
  faTiktok,
  faInstagram,
} from '@fortawesome/free-brands-svg-icons';

// Ajouter toutes les icônes à la bibliothèque globale
library.add(
  faChartLine,
  faFileAlt,
  faEye,
  faFileDownload,
  faCog,
  faChartBar,
  faPercentage,
  faPaperPlane,
  faRotateLeft,
  faImage,
  faLink,
  faAd,
  faServer,
  faClock,
  faSearch,
  faFilter,
  faFilePdf,
  faFileCsv,
  faTrophy,
  faUser,
  faLock,
  faUserShield,
  faHistory,
  faExclamationTriangle,
  faSignOutAlt,
  faUserPlus,
  faSave,
  faTrash,
  faHeart,
  faComment,
  faShare,
  faThumbsUp,
  faBars,
  faHome,
  faEnvelope,
  faPhone,
  faCalendar,
  faDownload,
  faUpload,
  faEdit,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  // Icônes de marques (réseaux sociaux)
  faYoutube,
  faFacebook,
  faTiktok,
  faInstagram,
);

export default library;